### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by naXa777** [JD-Software/JDeSurvey#13]
please fix the official website.
https://www.jdsoft.com/jdesurvey results in error 404 "Not Found".
https://www.jdsoft.com shows nginx welcome page.

**Comment by mmakroume** [comment]
It's fixed now. https://www.jdsoft.com/jd-esurvey.html
Thank you for the head up.

**Comment by naXa777** [comment]
@mmakroume the repo description and readme still point to a wrong location (http://www.jdsoft.com/jdesurvey -> 404)

**Comment by mpoussard-github** [comment]
That's fixed now too. Thanks again for the heads up.
