### ISSUE TITLE
PostgreSQL integration

### ISSUE THREAD

**Issue by romasochilov** [JD-Software/JDeSurvey#9]
We're using JDeSurvey and have desire to migrate database from MySQL to PostgreSQL, but there is no settings for such database source in options file. Is this migration possible at all?

**Comment by IntegrityKnight** [comment]
video at 1:20
https://vimeo.com/97945474

org.hibernate.dialect.PostgreSQLDialect
https://www.tutorialspoint.com/hibernate/hibernate_configuration.htm

**Comment by romasochilov** [comment]
Thanks for reply, @IntegrityKnight  .  I have checked the solution, which you suggested and everything is fine with connection

**Comment by romasochilov** [comment]
Also still there is an issue during psql integration with longtext fields in global_settings and velocity_templates tables.
